// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JKNBridge.ApotikOnline
{

    public class MetaDataDPHO
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("jmldata")]
        public string Jmldata { get; set; }
    }

    public class Obat
    {

        [JsonProperty("kodeobat")]
        public string Kodeobat { get; set; }

        [JsonProperty("namaobat")]
        public string Namaobat { get; set; }

        [JsonProperty("prb")]
        public string Prb { get; set; }

        [JsonProperty("kronis")]
        public string Kronis { get; set; }

        [JsonProperty("kemo")]
        public string Kemo { get; set; }

        [JsonProperty("harga")]
        public string Harga { get; set; }

        [JsonProperty("restriksi")]
        public string Restriksi { get; set; }

        [JsonProperty("generik")]
        public string Generik { get; set; }

        [JsonProperty("aktif")]
        public string aktif { get; set; }
    }

    public class ResponseDPHO
    {

        [JsonProperty("Obat")]
        public Obat[] Obat { get; set; }
    }

    public class RefDPHO
    {

        [JsonProperty("metaData")]
        public MetaDataDPHO MetaData { get; set; }

        [JsonProperty("response")]
        public ResponseDPHO Response { get; set; }
    }

}
