// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace JKNBridge.ApotikOnline
{

    public class MetaData
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public class Faskes
    {

        [JsonProperty("kode")]
        public string Kode { get; set; }

        [JsonProperty("nama")]
        public string Nama { get; set; }
    }

    public class Response
    {

        [JsonProperty("Faskes")]
        public Faskes[] Faskes { get; set; }
    }

    public class RefFaskes
    {

        [JsonProperty("metaData")]
        public MetaData MetaData { get; set; }

        [JsonProperty("response")]
        public Response Response { get; set; }
    }

}
