// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Sisrute
{

   public class Pasien
    {
        public string no_rm { get; set; }
        public string nama { get; set; }
        public string jenis_kelamin { get; set; }
        public string tempat_lahir { get; set; }
        public string tanggal_lahir { get; set; }
        public string no_telp { get; set; }
        public string nik { get; set; }
    }

    public class Medis
    {
        public string kode_pelayanan { get; set; }
        public string tanggal_registrasi { get; set; }
        public string alergi { get; set; }
        public string keluhan_utama { get; set; }
        public string riwayat_penyakit { get; set; }
        public string pemeriksaan_fisik { get; set; }
        public string pemeriksaan_penunjang { get; set; }
        public string kode_cara_keluar { get; set; }
        public string kode_keadaan_keluar { get; set; }
        public string nasehat_pulang { get; set; }
        public string kode_rs_rujukan { get; set; }
        public string nama_rs_rujukan { get; set; }
        public string jenis_rujukan { get; set; }
        public string nama_dokter { get; set; }
        public string tanggal_keluar { get; set; }
        public string tanggal_lanjutan { get; set; }
        public string diet { get; set; }
        public string kesadaran { get; set; }
        public string tekanan_darah { get; set; }
        public string suhu { get; set; }
        public string nadi { get; set; }
        public string frekuensi_nafas { get; set; }
        public string nama_ruang { get; set; }
        public string nama_kelas { get; set; }
        public string nama_cara_bayar { get; set; }
        public string skala_nyeri { get; set; }
    }

    public class Diagnosa
    {
        public string kode_icd10 { get; set; }
        public string keterangan { get; set; }
    }

    public class Tindakan
    {
        public string kode_icd9 { get; set; }
        public string keterangan { get; set; }
    }

    public class Obat
    {
        public string nama { get; set; }
        public string jumlah { get; set; }
        public string dosis { get; set; }
        public string cara_pemberian { get; set; }
        public string status_obat { get; set; }
    }

    public class Gambar
    {
        public byte[] file { get; set; }
        public string keterangan { get; set; }
    }

    public class PostResume
    {
        public Pasien pasien { get; set; }
        public Medis medis { get; set; }
        public Diagnosa[] diagnosa { get; set; }
        public Tindakan[] tindakan { get; set; }
        public Obat[] obat { get; set; }
        public Gambar[] gambar { get; set; }
    }

    /// <summary>
    /// Response untuk metode Post Resume Medis
    /// </summary>
    public class PostResumeResponse
    {
        public bool success { get; set; }
        public string kode_rsm { get; set; }
        public string kode_rujukan { get; set; }
        public string message { get; set; }
        public object[] log { get; set; }
    }

}
