// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Signature
{

    public class PostResumeResponse
    {
        public bool success { get; set; }
        public string kode_rsm { get; set; }
        public string kode_rujukan { get; set; }
        public string message { get; set; }
        public object[] log { get; set; }
    }

}
